<?php


namespace itDelightShippingFreeFrom;


use Shopware\Components\Plugin;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\UninstallContext;

class itDelightShippingFreeFrom extends Plugin
{
    public function install(InstallContext $context)
    {
        $context->scheduleClearCache(InstallContext::CACHE_LIST_ALL);
        parent::install($context); // TODO: Change the autogenerated stub
    }

    public function uninstall(UninstallContext $context)
    {
        $context->scheduleClearCache(UninstallContext::CACHE_LIST_ALL);
        parent::uninstall($context); // TODO: Change the autogenerated stub
    }

}